### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SpEcHiDe** [xditya/TGdetailsBot#2]
![image](https://user-images.githubusercontent.com/6317196/209143629-a5ac21f7-1665-4369-86cb-2fb71394a700.png)

![image](https://user-images.githubusercontent.com/6317196/209143695-8d87877d-21f6-44ab-890e-28ad8f8a756c.png)

- [x] Add color code to the displayed JSON, instead of simple mono 
- [x] Add Buttons to navigate different keys / arrays 
![image](https://user-images.githubusercontent.com/6317196/209144153-120df61e-8833-42ba-9953-3538afc716cd.png)

**Comment by xditya** [comment]
thanks for raising an issue :)

**Comment by SpEcHiDe** [comment]
better code: https://github.com/dcdunkan/show-json-bot
